weather:
  api:
    key: ${WEATHER_API_KEY}
server:
  port: 8081
  servlet:
    context-path: /journal
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_SECRET}
  cache:
    cache-names: weatherCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${MONGO_CLIENT_URI}
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
